#!/usr/bin/env python

# To run marietje, Python has to be able to find the separate packages.
# This script creates the proper symlinks.

import os
import sys
import os.path

def ensure_symlink(src, dst):
    if os.path.exists(dst):
        if not os.path.islink(dst) or os.readlink(dst) != src:
            print "`%s' already exists" % dst
        return
    os.symlink(src, dst)

def main():
    if len(sys.argv) != 2:
        print "Usage: create-py-symlinks [target]"
        return -1
    target = sys.argv[1]
    source = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    if not os.path.exists(target):
        print "`%s' does not exist" % target
        return -2
    def f(s, d):
        ensure_symlink(os.path.join(source, s), os.path.join(target, d))
    f('maried/src', 'maried')
    f('mirte/src', 'mirte')
    f('sarah/src', 'sarah')
    f('py-bertha/src', 'bertha')
    f('py-joyce/src', 'joyce')
    f('pymarietje/src', 'marietje')

if __name__ == '__main__':
    sys.exit(main())

# vim: et:sta:bs=2:sw=4:ft=python:
